name: CI

on:
  push:
    branches: 
      - '**'  # Runs on all branches
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install gtest manually
      run: sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp lib/*.a /usr/lib && sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
    - name: Create Build Directory
      run: mkdir -p build

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build Project
      run: cmake --build build

    - name: Run Tests
      run: |
        cd build
        ctest --output-on-failure
